### ISSUE TITLE
Some help with vcbuild

### ISSUE THREAD

**Issue by krisskross** [dw/py-lmdb#101]
Hi

I know this is a python project but please here me out. I'm trying to build LMDB with Java/JNI bindings with Visual C++ Project Builder 9.00.30729 (vcbuild) and saw a comment in ```setup.py``` that indicated that you solved the issues with building on windows.

```# Microsoft Visual Studio 9 ships with neither inttypes.h, stdint.h, or a sane```
```# definition for ssize_t, so here we add lib/win32 to the search path, which```
```# contains emulation header files provided by a third party. We force-include```
```# Python.h everywhere since it has a portable definition of ssize_t, which```
```# inttypes.h and stdint.h lack, and to avoid having to modify the LMDB source```
```# code. Advapi32 is needed for LMDB's use of Windows security APIs.```

I think stdint.h and inttypes.h is working for me. But unistd.h, which defines ssize_t, seems brooken. Since i'm not building for python I suspect that these cannot reused.

Any ideas or tips on how I can solve this issue?

https://github.com/deephacks/lmdbjni/tree/master/lmdbjni-win64/headers
https://github.com/deephacks/lmdbjni/blob/master/lmdbjni/src/main/native-package/vs2010.vcxproj

**Comment by dw** [comment]
Hi there,

All Python does in this case is `#define` it to `__int64`. You could do that from the command-line, whatever the MSVC equivalent is to `-Dssize_t=__int64`, or similar.

If you can't make this work for yourself, please open an ITS bug with OpenLDAP upstream. It's really kindof silly every user must individually hack around it on Windows.
