### ISSUE TITLE
Wheels for Python 3.5

### ISSUE THREAD

**Issue by oberstet** [dw/py-lmdb#103]
py-lmdb provides wheels (which is highly appreciated!): would be nice to have wheels for Python 3.5 too.

**Comment by dw** [comment]
Presumably you want them for Windows?

**Comment by oberstet** [comment]
That's the main use case, yeah.

We (https://github.com/crossbario/crossbar), want to depend on LMDB for some upcoming features, and we have a Windows user base (mainly devs testing on desktop). And that user base is not necessarily Pythonistas that are fine with installing the required tool chain to build binary extensions.

**Comment by dw** [comment]
Currently battling with the 3.5 installer :) Might have wheels done shortly assuming they haven't changed the Visual Studio version again.

**Comment by oberstet** [comment]
Fantastic! Thank you very much.

**Comment by dw** [comment]
Naturally they've upgraded the compiler again. Installing 12gb now ;(   Should have new wheels cut sometime this evening

**Comment by dw** [comment]
https://pypi.python.org/pypi/lmdb/0.88
