### ISSUE TITLE
LMDB 0.9.18 has been released

### ISSUE THREAD

**Issue by pdedmon** [dw/py-lmdb#107]
https://github.com/LMDB/lmdb/releases/tag/LMDB_0.9.18

It would be great to see this included.

**Comment by dw** [comment]
Hi there,

http://lmdb.readthedocs.org/en/release/#changelog

https://pypi.python.org/pypi/lmdb/0.89

Take care

**Comment by pdedmon** [comment]
Awesome, much appreciated!
