### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by tpetazzoni** [dw/py-lmdb#108]
The comment header in each source file indicates:

```
# A copy of this license is available in the file LICENSE in the
# top-level directory of the distribution or, alternatively, at
# <http://www.OpenLDAP.org/license.html>.
```

Unfortunately, there is no LICENSE file in the top-level directory. While the link http://www.OpenLDAP.org/license.html works, it points to the latest version of the OpenLDAP license, so which potentially changes over time, so we cannot be sure under which version of the OpenLDAP license py-lmdb is released.

**Comment by tpetazzoni** [comment]
My apologizes,  there is a LICENSE file in the Github repository, but not in the tarballs available at https://pypi.python.org/pypi/lmdb/0.88.

**Comment by dw** [comment]
Thanks, no doubt a problem with MANIFEST.in, will tweak before next release
