### ISSUE TITLE
`--txn_size` option ignored in lmdb.tool?

### ISSUE THREAD

**Issue by achalddave** [dw/py-lmdb#116]
It seems that the `--txn_size` option [documented here](https://lmdb.readthedocs.io/en/release/#command-line-tools) isn't used anywhere. I'd submit a PR to remove it from the documentation/the option parser, but I'm not sure if I'm just not seeing where it's used, or whether that option should be used but isn't?

**Comment by dw** [comment]
Hi there,

Thanks for the report and sorry about the huge delay in replying. I've removed the option, as it was intended for use with "lmdb.tool edit" command, and a helper class that I failed to ever implement in a sensible fashion.

Additionally in the meantime, lmdb itself has grown much better support for handling huge transactions. A few years ago it was much more likely to bump into some of the library's hard transaction size limits, but this is no longer an issue.

Thanks again for the report.
