### ISSUE TITLE
Conveting mnist data to lmdb with python results very large database

### ISSUE THREAD

**Issue by twmht** [dw/py-lmdb#123]
I am currently playing the lenet model provided by caffe.

the example (which is in path/to/caffe/examples/mnist/convert_mnist_data.cpp provides a c++ program to convert the mnist data to lmdb.

I write a python program to do the same thing, but the size (480MB) of lmdb is much larger than the one converted by c++ (60MB).

the test accuracy is almost the same (98%).

Why the size differs a lot?

Here is the program. I utilize the mnist module (https://pypi.python.org/pypi/python-mnist/) to help load the binary mnist data.

```
from mnist import MNIST
import numpy as np
import cv2
import lmdb
import caffe
mndata = MNIST('./data')
images, labels = mndata.load_training()
labels = np.array(labels)
images = np.array(images).reshape(len(labels), 28, 28).astype(np.uint8)

print type(images[0][0][0])

count = 0
env = lmdb.open('mnist_lmdb', map_size=1000*1000*1000)

txn = env.begin(write=True)
for i in xrange(len(labels)):
    print i
    datum = caffe.proto.caffe_pb2.Datum()
    datum.channels = 1
    datum.height = 28
    datum.width = 28
    datum.data = images[i].tobytes()
    datum.label = labels[i]
    str_id = '{:08}'.format(i)
    txn.put(str_id, datum.SerializeToString())

    count = count + 1

    if count % 1000 == 0:
        txn.commit()
        txn = env.begin(write=True)

if count % 1000 != 0:
    txn.commit()
env.close()
```

thank you.

**Comment by dw** [comment]
Please ensure you are starting from an empty environment -- LMDB does not return unused space to the OS.

Secondarily, please instrument both programs to write something like the following to stdout just before every call to put():

````
"put() key=NNNNNNNN dlen=NN"
````

Where `key` is the actual key and dlen is the data length. Save both stdout logs and run them through diff. If both programs are generating exactly the same write pattern, then compare the version of LDMB CAFFE is using vs the version py-lmdb is compiled with. If both match, please upload the logs you generated above and reopen this ticket.
