### ISSUE TITLE
Docs are newer (0.9) than latest release on pypi(0.89)

### ISSUE THREAD

**Issue by ddorian** [dw/py-lmdb#125]
On pypi it's 0.89 on http://lmdb.readthedocs.io/en/release/#changelog it's 0.9

**Comment by dw** [comment]
Thanks for spotting this. I screwed up the 0.90 release and you just found a bunch of bits I forgot to clean up :)  Docs should now be for 0.89, and release brand also reset to 0.89.

Thanks again!
