### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by milaz** [dw/py-lmdb#126]
There is a memory corruption issue related to `Cursor.set_range_dup` method and the way key field is retained in a Cursor object of the wrapper. The example follows.

```
import lmdb

db = lmdb.open('./db', map_size=2*1024*1024, max_dbs=1)    
b1 = db.open_db(b'B1', dupsort=True)
with db.begin(write=True) as tx:            
    A = b'\x00\x00\x00\x00\x00\x01'
    B = b'\x00\x00\x00\x00\x00\x02'
    C = b'NNN'
    tx.put(B + C, A, db=b1)
    tx.put(B + C, B, db=b1)
    
    cur = tx.cursor(b1)
    val = b'\x00'
    
    def fn():
        key = B + C
        print(cur.set_range_dup(key, val))

    fn()
    print('Normal', cur.key())
    range(2) # the key memory gets overwritten here
    print('Corrupted', cur.key())
```

**Comment by dw** [comment]
Thanks for the report and short reproduction, this is a huge time saver. I'm away for the weekend but should be able to look at this on Monday evening.

**Comment by dw** [comment]
Hey there,

Thanks for reporting this, it seems a bug in MDB_GET_BOTH_RANGE, where it fails to update `key` and `value` on success. This seems to be an upstream bug, but py-lmdb master has a workaround for it in any case.
