### ISSUE TITLE
env.begin() raises BadRSlotError after operations on another environment

### ISSUE THREAD

**Issue by richardtsai** [dw/py-lmdb#129]
Minimal failing example:

```py
import lmdb

env1 = lmdb.open('/tmp/test.db')
with env1.begin() as txn:
    txn.get(b'key')

with lmdb.open('/tmp/test.db') as env2:
    with env2.begin() as txn:
        txn.get(b'key')

with env1.begin() as txn:  # BadRSlotError
    txn.get(b'key')
```

py-lmdb 0.89 with bundled lmdb, Python 3.5.2 on macos

I haven't tested with lmdb C-API. I am not sure if it is desired or an issue.

**Comment by dw** [comment]
Hi there,

Due to limitations of the UNIX file locking APIs available to LMDB, opening the same database multiple times in a single process is not supported. From `lmdb.h`:

````
 *  - Do not have open an LMDB database twice in the same process at
 *    the same time.  Not even from a plain open() call - close()ing it
 *    breaks flock() advisory locking.
````

**Comment by dw** [comment]
Sorry, I should have added, I've investigated 'fixing' this in the binding in the past, but it requires keeping track of all open environments and their pathnames, and reimplementing some of LMDB's logic for building pathnames.

I really don't like the behaviour you experienced (and I've looked at fixing it previously), but not sure if there is a good approach to it

**Comment by richardtsai** [comment]
Well, the error message is kinda misleading to me. But it is not hard to workaround in the users' aspect as long as the limitation is aware. I think you can just leave it to the users, not to mention it is rare to open plenty of different databases in one process. But I guess you may need to point it out in the documentations. Thanks!  (ง •̀_•́)ง
