### ISSUE TITLE
PyPI package doesn't include test suite

### ISSUE THREAD

**Issue by pitrou** [dw/py-lmdb#137]
The source package on PyPI doesn't include the test suite. This makes it more cumbersome for external packagers to run it automatically (reference: https://github.com/conda-forge/staged-recipes/pull/1809).  A possible solution would be to include the tests in `MANIFEST.in`.

### Affected py-lmdb Version

0.92

**Comment by dw** [comment]
Hi,

Can you live without a new source tarball release? I have to rebuild the corresponding Windows binaries which is a pain preferably avoided

**Comment by pitrou** [comment]
Oh, sure, I can definitely live without it :-)
