### ISSUE TITLE
putmulti does not raise MapFullError 

### ISSUE THREAD

**Issue by mglaezer** [dw/py-lmdb#140]
Trying to insert ~1000 records with curs.putmulit() with default named parameters and providing some Iterable[bytes, bytes]

Depending on map_size setting, it either raises MapFullError (which is a correct behavior) if map_size is relatively low to insert ~250 records or inserts only ~250 records without raising the exception and not inserting the rest ~750 records (which is unexpected behavior).

If map_size is enough to insert the records, everything is done correctly.

Strangely, the same invocation in the same conditions works properly (either inserting all records or raising MapFullError) if instead of Iterable I provide List.

**Comment by dw** [comment]
Are you using CFFI or the CPython extension?

**Comment by dw** [comment]
Please also indicate the specific map_size= values that trigger the condition, and the lengths of your keys and values
