### ISSUE TITLE
Non useable in Solaris (solved already in master, please do a release)

### ISSUE THREAD

**Issue by jcea** [dw/py-lmdb#142]
LMDB version included in py-lmdb 0.92, current release doesn't work in solaris 11/Solaris derivatives like Illumos. The fix is already committed in master LMDB and, in fact, it is already included in master py-lmdb: https://github.com/dw/py-lmdb/blob/master/lib/mdb.master/mdb.c#L4997

Can I request a new release containing that fix?. Thanks!.

More details:

https://github.com/joyent/pkgsrc/issues/431
https://github.com/LMDB/lmdb/commit/c367c1f69685a4d307acb8cea6945c1d67e1cc7e

**Comment by dw** [comment]
Hi @jcea,

The recent changes in py-lmdb to support the master branch are not ready yet, due to linking issues on Windows I haven't had time to straighten out yet. I will hopefully get a chance to sort it out this weekend, after which a new "lmdb_master" Python package will exist that installs the master branch branch.

**Comment by jcea** [comment]
Any news? :-)

**Comment by dw** [comment]
Sorry dude,

The lack of sunlight these past 2 months has severely impacted my productivity. There is stuff on master, but it is too complicated for all it is supposed to be doing, feel free to work at it.

The remaining problem is the linking to the kernel APIs doesn't work properly for 32bit. Upstream are chatting about replacing those static links with GetProcAddress() but I don't think anything is on mdb.master yet.

Will pick this up when I have the energy, but I really don't know when that will be, sorry.

**Comment by dw** [comment]
Looks like nobody has done anything to mdb.master yet. The GetProcAddress stuff is actually a really easy change, I can rip out most of the crap on py-lmdb master once it's done. If you're feeling adventurous and know a bit of C, maybe submit a patch to OpenLDAP ITS instead :)

**Comment by jnwatson** [comment]
py-lmdb has been updated.
