### ISSUE TITLE
error trying to install in cygwin on windows 10

### ISSUE THREAD

**Issue by FeralWhippet** [dw/py-lmdb#143]
* cygwin on Windows 10
* python3 -m pop install lmdb
    ...
    lib/mdb.c:4625:49: error: ‘PTHREAD_MUTEX_ROBUST’ undeclared (first use in this function)
        || (rc = pthread_mutexattr_setrobust(&mattr, PTHREAD_MUTEX_ROBUST))

**Comment by dw** [comment]
I have zero interest in supporting Cygwin, sorry.
