### ISSUE TITLE
TypeError: expected a readable buffer object on a put operation

### ISSUE THREAD

**Issue by mayurjain0312** [dw/py-lmdb#145]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    0.92

### py-lmdb Installation Method

     sudo pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

(0, 9, 18)

### Machine "free -m" output

             total       used       free     shared    buffers     cached
Mem:         15801      14727       1073          0        673       8134
-/+ buffers/cache:       5919       9882
Swap:        15803        236      15567

### Other important machine info

Running under cgroups? Containers? Weird filesystems in use? Network
filesystem? Patched kernel? ...

### Describe Your Problem

Getting the following error:
TypeError: expected a readable buffer object

with self.lmdb_env.begin(write=True) as txn:
            txn.put(record_key, record_value)

record_key = 1
record_value = some bytes

### Errors/exceptions Encountered

Traceback (most recent call last):
  File "tiftempstuff.py", line 158, in <module>
    main()
  File "tiftempstuff.py", line 63, in main
    tifobj.write_record(orig_image_data, additional_image_data_list, annotation_data, key)
  File "/local/mnt/workspace/mayurj/mjtest/tif/tif.py", line 71, in write_record
    txn.put(record_key, record_value)
TypeError: expected a readable buffer object

### Describe What You Expected To Happen

e.g.

I expected the transaction to commit successfully.

### Describe What Happened Instead

e.g.

The Python process crashed.

**Comment by dw** [comment]
Please refer to the documentation. Keys and values must be bytestrings (type "str" in Python 2.0, type "bytes" in Python 3.0).
