### ISSUE TITLE
Running "warm" from the shell fails and prints a traceback under Python 3

### ISSUE THREAD

**Issue by dev351** [dw/py-lmdb#148]
### Affected Operating Systems

* Linux (other OS's not tested)

### Affected py-lmdb Version

    0.92

### py-lmdb Installation Method

    pip install lmdb    # into an active Python3.5.1 virtual environment

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

    >>> print(lmdb.version())
    (0, 9, 18)

### Describe Your Problem

When attempting to run the "warm" command the lmdb tool exits with an error and a Python traceback is displayed.
Command used:

    python3 -mlmdb warm --env PATH/TO/ENVIRONMENT

### Errors/exceptions Encountered

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".virtualenvs/<virtual_env_dir>/lib/python3.5/site-packages/lmdb/__main__.py", line 24, in <module>
    lmdb.tool.main()
  File ".virtualenvs/<virtual_env_dir>/lib/python3.5/site-packages/lmdb/tool.py", line 607, in main
    func(opts, args[1:])
  File ".virtualenvs/<virtual_env_dir>/lib/python3.5/site-packages/lmdb/tool.py", line 471, in cmd_warm
    buf = array.array('c', '\x00' * bufsize)
TypeError: cannot use a str to initialize an array with typecode 'c'

```

### Describe What You Expected To Happen
(using lmdb under Python2)
    $ python2 -mlmdb warm --env PATH/TO/ENVIRONMENT
    Warmed 5942.00mb in 6902ms

I'd expect the command to work with similar output under Python3. Appears this command was not tested under Python 3. The 'c' typecode passed into array.array('c',...) is only supported under Python2.

### Describe What Happened Instead

Shell exit status of 1 and a Python traceback is printed

**Comment by dw** [comment]
This is fixed on master, but it'll take a while to make it into a release, as there is a big incomplete change sitting on master
