### ISSUE TITLE
Cannot put() data > 511 bytes when using a named database

### ISSUE THREAD

**Issue by mklemm2** [dw/py-lmdb#152]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

* 0.92

### py-lmdb Installation Method

Homegrown RPM

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

CentOS 6.8
Python 3.4
(0, 9, 18)

### Describe Your Problem

Works:

```
import lmdb

with lmdb.open('/tmp/testdb', max_dbs=20, writemap=True) as env:
  db = env.open_db(key=b'test', dupsort=True, dupfixed=False)
  with env.begin(db=db, write=True) as txn:
    txn.put(b'MYKEY', b'511 bytes 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901', dupdata=True)
```

Doesn't work:

```
import lmdb

with lmdb.open('/tmp/testdb', max_dbs=20, writemap=True) as env:
  db = env.open_db(key=b'test', dupsort=True, dupfixed=False)
  with env.begin(db=db, write=True) as txn:
    txn.put(b'MYKEY', b'512 bytes 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012', dupdata=True)
```

Works, again, if not using a named database:

```
import lmdb

with lmdb.open('/tmp/testdb', max_dbs=20, writemap=True) as env:
  db = env.open_db(dupsort=True, dupfixed=False)
  with env.begin(db=db, write=True) as txn:
    txn.put(b'MYKEY', b'512 bytes 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012', dupdata=True)
```

### Errors/exceptions Encountered

```
Traceback (most recent call last):
  File "/home/vagrant/test2.py", line 6, in <module>
    txn.put(b'TEST-EVENT146', b'512 bytes 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012', dupdata=True)
lmdb.BadValsizeError: mdb_put: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
```

**Comment by snuxoll** [comment]
When using LMDB in multi-database mode the master database stores the names of the sub-databases are stored as keys in the unnamed database. If you open a LMDB database in this mode, you MUST NOT modify any data in the unnamed database.

**Comment by snuxoll** [comment]
I'm confused as to why it lets you write 512 bytes in the unnamed database at all, the LMDB documentation on the [MDB_Val struct](http://www.lmdb.tech/doc/group__mdb.html#structMDB__val) specifically states values in MDB_DUPSORT databases must be no longer than the max key size (which is 511 by default).

If you want to store more, you'll have to modify your lmdb build to increase the keysize.

**Comment by mklemm2** [comment]
> I'm confused as to why it lets you write 512 bytes in the unnamed
> database at all

It seems like you can't open the default database in dupsort mode! Since it is always open, my  `db = env.open_db(dupsort=True, dupfixed=False)` call does nothing but return the handle.

> the LMDB documentation on the MDB_Val struct specifically states values
> in MDB_DUPSORT databases must be no longer than the max key size

That's a pretty heavy limitation that should be stated way more prominent in the docs! Especially compared to the 4G limit of normal, non-duplicate values!

**Comment by dw** [comment]
@mklemm2, dupsort is primarily intended for implementing secondary indices where the value part is intended to be a short bytestring primary key to be looked up in a main database. What is your use case for such huge values? The feature is really not intended for that, but it's possible you can add a layer of indirection (using the secondary index approach) to support your use case.

I agree this is at least a documentation bug, although the docs do already note that you should be referring to the underlying Doxygen documentation.

Regarding opening the main database with weird flags, that's a bad idea as it breaks named databases in that environment. py-lmdb's current behaviour is suboptimal (it's basically a silent failue), but I think lmdb itself has significant restrictions on what flags can be set for the main database anyway

**Comment by snuxoll** [comment]
@mklemm2
If you pass in max_db's to the environment you should never open the unnamed database in general, in multi-database mode it is where the names of named databases are stored.

**Comment by mklemm2** [comment]
@dw Yes, that's exactly what I did after I discovered that my first approach will not work. I'm not complaining about the design of lmdb, I just wished this limit would have been stated somewhere where a lmdb newbie like me finds it right from the start and not only in the documentation of some underlying C function.

If you read through the feature set of the lmdb library and the documentation of this (otherwise great) python module, you mostly see that:

a) values can be up to 4G in size and
b) you can have duplicates, e.g. multiple values per key

My usecase is to store JSON "deltas" that I receive on a HTTP endpoint and later merge them using the https://github.com/avian2/jsonmerge module. The deltas usually are about 1-2K in size, so yes, increasing the limit by recompiling would have been an option but is not necessary, anymore.

LMDB and this python module has given me roughly 50x the performance I need right now, so thanks! I make a sport out of writing stuff in python and still be more performant then my colleagues' Java implementations while using 90% less memory (and lines of code) and you helped me to another win on that front.

@snuxoll My second approach was to use multiple database files without any named databases. But as I said, because the unnamed database is always open, you can't open it again in dupsort mode. So dupsort always requires a named database.

Now I'm using three named databases, one as actual data store to save my objects with unique keys, one in dupsort mode as index and a third one to save the time of the last modification.
