### ISSUE TITLE
lmdb's size is much larger than the actual data

### ISSUE THREAD

**Issue by twmht** [dw/py-lmdb#154]
Edit this issue template as appropriate. If none of it seems relevant to your
issue, then you may delete the entire template, however, I may not respond to
issues that do not include important information that is mentioned in this
template!

### Affected Operating Systems
* Windows

### Affected py-lmdb Version
0.92

### py-lmdb Installation Method

pip install lmdb

I want to write the images into lmdb, all the images are 40MB, but the resulting lmdb exceeds 500MB.

Here is the code

```
env = lmdb.open(dataDir, map_size=1000*1000* 500)
txn = env.begin(write=True)

for image in images:
    // read image into pixData
    txn.put(str(index).encode('ascii'), pixData)
    index = index + 1

    if index % 100 == 0:
        logger.info('Writing images {}'.format(index))
        txn.commit()
        txn = env.begin(write=True)


if index % 100 != 0:
    txn.commit()
```

why is the size is much larger (and a lot)  than I expected?

thanks!

**Comment by Boxie5** [comment]
@twmht why is this issue closed, please?

I'm also facing this.

Leave out the difference between compressed image and uncompressed image, when I set the same resize width and height, the size of  lmdbs  I get with `caffe/tools/convert_imageset` are much more smaller than that with `py-lmdb`.

**Comment by twmht** [comment]
@Boxie5 

I close the issue because I miscompare the compressed images (40MB) and uncompressed images (larger than 40MB).
