### ISSUE TITLE
In-place compacting

### ISSUE THREAD

**Issue by h5rdly** [dw/py-lmdb#156]
Hi,

First, thank you for this well made package. I'm getting to know my way around LMDB, so I apologize if this a silly question, but I wanted to ask whether it is possible to compact the database without going through copy(). 
What I currently do is use copy(), delete the original database, and rename the compacted database back to the original name. Sorry if this is something obvious that I miss due to my noobness, but I was wondering whether prehaps it would be feasible to add something like a compact() method to use with py-lmdb.

Thanks :)

**Comment by dw** [comment]
Hi there,

Unfortunately it is not possible to shrink the data file after it has grown, as there is no way to signal to concurrent readers that their memory maps now extend past the end of file. This has been discussed for years, but there is no easy solution.
