### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by ofek** [dw/py-lmdb#158]
@dw Are there plans to ship a new release soon, with py36 wheels?

**Comment by dw** [comment]
Hi there,

Do you mean wheels for Windows? If so, sure, I'll look into it shortly. There is some stuff sitting in master that I have to sift through before I can cut a release, but I could also just upload the current version for 3.6 if that's fine with you

**Comment by ofek** [comment]
I'm ok with waiting until you sort master out. Do you think you'd have time for a new release by June?

**Comment by ofek** [comment]
@dw Could you please do what you suggested and just upload the current version for 3.6?

**Comment by dw** [comment]
Hi there,

32/64bit wheels/eggs have been uploaded for 3.6. Let me know if you have any further issues.

**Comment by ofek** [comment]
Thank you!
