### ISSUE TITLE
Multiprocessing with lmdb

### ISSUE THREAD

**Issue by dineshbvadhia** [dw/py-lmdb#159]
I want to use the multiprocessing ProcessPoolExecutor method to read key values from an lmdb db, and send the value to n_cpu_cores, and return the result. This is the code but it generates an error and I'm not sure why. Do you know what is going on?

```
import concurrent.futures as cf
import lmdb

env = lmdb.open(path, map_size, writemap=True)

with cf.ProcessPoolExecutor(max_workers=n_cpu_cores) as executor:
    with env.open_db("fv".encode('utf-8')) as txn:
        fs = [executor.submit(do_this_function, value) for value in [txn.get(key) for key in keys]]
        for future in cf.as_completed(fs):
            r = future.result()
```
Error message: mdb_dbi_open: MDB_DBS_FULL: Environment maxdbs limit reached

max_dbs=8 remains as the default. Thanks.

**Comment by dw** [comment]
Hi there,

lmdb.Environment must be instantiated in each process you wish to access
the database from, it cannot be shared across forks. Unfortunately unlike
the multiprocessing module that it is built on, ProcessPoolExecutor
provides no support for running code once for each new process, which would
be required to use concurrent.futures effectively here.

You could investigate using the multiprocessing module directly, or perhaps
simply reopen the database prior to each lookup (although this will come
with quite a performance penalty).

I will leave this bug open and investigate adding richer error messages
around fork(), as the error you are receiving is not explaining the real
problem.

**Comment by dineshbvadhia** [comment]
Ah, that explains it. Also a drag it cannot be achieved. Will investigate the multiprocessing module. Must be a way of doing this!

**Comment by dw** [comment]
you could subclass ProcessPoolExecutor and override its
_adjust_process_count method to run a wrapped version of the child main(),
the wrapped version would setup a lmdb.Environment global for you to use.
Ugly, but it'd  work. multiprocessing has Pool hooks specifically for doing
this kind of thing in a much neater way.

Oh, a simpler option would be something like this:

````
import threading

_tls = threading.local()


def get_env():
   try:
      return _tls.env
   except AttributeError:
      _tls.env = lmdb.open(...)
      return _tls.env
````


It'll still have some overhead, but it's better than messing around in
concurrent.futures implementation ;)

**Comment by dineshbvadhia** [comment]
Will have a closer look. Note I want to run multiple processes (so, ProcessPoolExecutor) and not threads (ie. not ThreadPoolExecutor).

**Comment by dw** [comment]
The effect will be the same: each new process will have a unique thread
identity, and so the function will DTRT

**Comment by dineshbvadhia** [comment]
Sorry, for being dumb but how would the get_env() function be used in my code?

**Comment by dw** [comment]
call it in every place you'd reference the environment instance. It'll
lazily create it on first access, either in the parent process or any
children

**Comment by dineshbvadhia** [comment]
Do you mean:

```
import concurrent.futures as cf
import lmdb
import threading

_tls = threading.local()

def get_env(path, map_size):
   try:
      return _tls.env
   except AttributeError:
      _tls.env = lmdb.open(path, map_size, writemap=True)
      return _tls.env
      
with cf.ProcessPoolExecutor(max_workers=n_cpu_cores) as executor:
    env = get_env(path, map_size)
    with env.open_db("fv".encode('utf-8')) as txn:
        fs = [executor.submit(do_this_function, value) for value in [txn.get(key) for key in keys]]
        for future in cf.as_completed(fs):
            r = future.result()
```
Because it still generates the same error.

**Comment by dineshbvadhia** [comment]
I guess there isn't a solution to this problem. Tried the above suggestions but it didn't work out.

**Comment by dw** [comment]
Hi Dinesh,

I'm extremely busy with real work at present and don't have time to write examples for you. Please investigate an alternative method for ensuring each process pool worker has a private lmdb.Environment() instance that was not inherited from the parent. The #python IRC channel on Freenode may be able to help you
