### ISSUE TITLE
lmdb becomes so slow when data amount get huge

### ISSUE THREAD

**Issue by Pinnh** [dw/py-lmdb#162]
When put about 1300 datum in one db, the reading speed of lmdb is so quick(0.177ms/data,if there is nothing wrong).but when I put about 1200000 datum in one db, the reading speed only 0.02s/data (every data is about 0.17M,db is about 200G), which is so slow.
Is there any way to speed up? thanks.

System: Linux/Ubuntu
Version: 0.92
Install Method: sudo pip install lmdb
Bundled  LMDB library

```
              total        used        free      shared  buff/cache   available
Mem:           7944        2359         773          46        4811        5195
Swap:          8151           0        8151

```

**Comment by kawing-chiu** [comment]
IMHO sharding is the way to go. Even though lmdb is fast, it is still based on B+ tree, which is of log(n) complexity on common operations. So speed degrades when the db is extremely large.

**Comment by Pinnh** [comment]
OK，thanks.
