### ISSUE TITLE
corrupt lmdb generation on windows

### ISSUE THREAD

**Issue by x0v** [dw/py-lmdb#166]
### Affected Operating Systems

* Windows 10

### Affected py-lmdb Version

    `print lmdb.__version__ = 0.92`
     

### py-lmdb Installation Method

       `conda install -c conda-forge python-lmdb`

### Using bundled or distribution-provided LMDB library?

       Bundled (sorry but I am not sure what this exactly means but I am using Anaconda python)

### Distribution name and LMDB library version

      `lmdb.version  = (0,9,18)`

### Machine "systeminfo" output

![](https://s2.postimg.org/t6q2d4yc9/Screen_Shot_2017-08-09_at_3.02.14_PM.png)

### Describe Your Problem

I am generating image segments and then trying to create lmdb dataset from them.
The sample image segment is like ![this](https://s2.postimg.org/fwnyaj8bd/image.jpg)

The script I am using to generate lmdb out of images is [this](https://github.com/bgshih/crnn/blob/master/tool/create_dataset.py)
I have also tried changing `map_size` in line 37 to be `4294967296 `

### Errors/exceptions Encountered

No exception or error is happening. The console says lmdb successfully generated.

### Describe What You Expected To Happen

e.g.

I expected the lmdb size to differ when I generate for 1000 images contrary to when I generate for 10 images.

### Describe What Happened Instead

e.g.

Generated lmdb is always of same size, irrespective of number of images used. Size of generated lmdb is always the one I specify in line 37 of [this script](https://github.com/bgshih/crnn/blob/master/tool/create_dataset.py).

Moreover thereafter what happens because of this is whenever I put to use the generated lmdb for training, it doesn't train and says this error

```
 /home/ubuntu/torch/install/share/lua/5.1/image/init.lua:254: JPEG datastream contains no image
stack traceback:
    [C]: in function 'load'
    /home/ubuntu/torch/install/share/lua/5.1/image/init.lua:254: in function 'decompress'
    ./DatasetLmdb.lua:74: in function 'callback'
    ../third_party/lmdb-lua-ffi/src/lmdb.lua:239: in function 'transaction'
    ./DatasetLmdb.lua:65: in function 'allImageLabel'
    ./training.lua:128: in function 'trainModel'
    main_train.lua:51: in main chu nk
    [C]: in function 'dofile'
    ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x004065d0
```

While this never happens on Ubuntu (wherein I use same dataset and same scripts).
I have also seen this (issue](https://github.com/dw/py-lmdb/issues/85) where it is suggested to use sparse patch branch of lmdb repo. I tried that as well but nothing changes for me.

Please help.

**Comment by jnwatson** [comment]
LMDB preallocates filesystem space of the provided mapsize so it doesn't have to worry about running out of disk space and so it can map the file directly into memory, so it is actually expected that the file doesn't change size (on Windows; most Linux filesystems handle sparse files just fine, so the disk usage will actually change).

You might try using the lmdb tool (python -m lmdb) to see if your data actually made it into the database.

**Comment by benrg** [comment]
> it is actually expected that the file doesn't change size (on Windows; most Linux filesystems handle sparse files just fine, so the disk usage will actually change).

Most Windows filesystems* handle sparse files just fine. Files just aren't sparse by default: You have to use the `FSCTL_SET_SPARSE` ioctl after creating them.

\* (i.e., NTFS, which is what almost everyone uses)

If LMDB expects a file to be sparse, and doesn't set it to be sparse on Windows, that's a bug in LMDB.

I suppose it isn't a bug in py-lmdb as such, but I think this issue shouldn't be closed as completed as long as the bug still exists. It makes py-lmdb practically useless for many purposes on Windows.

**Comment by jnwatson** [comment]
The challenge is that this is an upstream issue. Until lmdb fixes it, my hands are tied.
