### ISSUE TITLE
Interpretation of boolean keyword arguments too strict

### ISSUE THREAD

**Issue by jnwatson** [dw/py-lmdb#168]
The following code will crash with a double free (Mac OS 10.12, python3.6, but should apply to everything):
```python
import lmdb
env = lmdb.Environment('test.lmdb', lock=1)
txn1 = env.begin(write=True)
txn2 = env.begin(write=True)
del env
del txn1
del txn2
```

The problem is that the `1` after the `lock` keyword argument is being compared to `Py_True`, which evaluates to false, so locking will be disabled. I confirmed this in a debugger.

Line of code where comparison takes place:
https://github.com/dw/py-lmdb/blob/master/lmdb/cpython.c#L691

**Comment by dw** [comment]
o...m...g...  sooo sorry about this, totally my fault, and I knew what I was doing when I wrote that code. So stupid!

**Comment by dw** [comment]
Just one last note on this: it's a perfect example of why you should always try your code with LMDB_FORCE_CFFi=1 set in the environment. A nice side effect of the package's implementation is that it isn't just a single implementation, so you can very easily isolate bugs like this one just by flicking an environment variable.

**Comment by jnwatson** [comment]
Good point. I'll keep that in mind.
