### ISSUE TITLE
Is there a direct way to get all keys other than iterating over the cursor?

### ISSUE THREAD

**Issue by Notmeor** [dw/py-lmdb#191]
Is there a direct way to get all keys other than iterating over the cursor? 
haven't found a method like 'list_keys' in the doc

### Affected Operating Systems

* Linux
* Windows
* BSD
* [Other]

### Affected py-lmdb Version

    0.94

**Comment by dw** [comment]
`list(cursor.iternext_nodup())` is probably the closest match, and offers minimal speed penalty over an explicit helper. Note that enumerating all keys is not a useful operation for databases that grow larger than RAM, and in LMDB, "all keys" may mean either "all keys (no duplicates)" or "all keys (including duplicates)".
