### ISSUE TITLE
Allow setting page size at database creation time

### ISSUE THREAD

**Issue by jcea** [dw/py-lmdb#57]
Currently lmdb seems to be automatically selecting a block size, 4096 bytes in my case. I would like to be able to select a bigger page size, like 64KB. Useful to reduce internal fragmentation and for ZFS recordsize matching, for instance.

Thanks!.

**Comment by dw** [comment]
Hi there,

Closing this ancient issue as there is very little I can do in the binding until upstream supports it. :)

Thanks for the report.
