### ISSUE TITLE
Add support for ```mdb_set_compare``` (and maybe ```mdb_set_dupsort```)

### ISSUE THREAD

**Issue by amirouche** [dw/py-lmdb#79]
Héllo,

I've been lurking around the documentation and it's seems like there is no support for  ```mdb_set_compare``` [1] and ```mdb_set_dupsort``` [2].

[1] http://symas.com/mdb/doc/group__mdb.html#ga68e47ffcf72eceec553c72b1784ee0fe
[2] http://symas.com/mdb/doc/group__mdb.html#gacef4ec3dab0bbd9bc978b73c19c879ae

I don't know what is the interest of ```mdb_set_dupsort``` yet (maybe you do?).

```mdb_set_compare``` is very useful to create indexes and then doing range queries. Here is an example, that I've extracted from a project using bsddb. Index is indexing every property of the objects I store in another database. The index allows to query over the attribute values without loading every single object ie. it's an index. The following snipped doesn't show it but the compare fonction is set to tuple comparison, which looks like the following:

```python
def compare_keys(a, b):
    a = msgpack.loads(a)
    b = msgpack.loads(b)
    return cmp(a, b)
```

Except there is no ```cmp``` function in python 3.

Here is the lookup fonction:

```python
from collections import namedtuple


cursor = index.cursor()

# Entries have the following format:
#
#  (attribute_name, value, identifier) -> ''
#
# Where identifier is the identifier of a document
# with ``attribute_name`` set to ``value``.
# Value is always the empty string, I did not find an interest on using it.

KeyIndex = namedtuple('KeyIndex', ('attribute', 'value', 'identifier'))


def lookup_documents_identifiers(attribute, value):
    # The identifier placeholder is set to the empty
    # string so that the cursor will be positioned at the first
    # key found for the combination of ``attribute``
    # and ``value`` if any, because the empty strings is the
    # smallest string value and the index is sorted.
    lookup = KeyIndex(attribute, value, '')
    next = cursor.set_range(dumps(lookup))

    while next:
        key, _ = next  # value is a useless empty string
        key = KeyIndex(*loads(key))
        # check that key is within bound of the lookup
        if (key.attribute == lookup.attribute
            and key.value == lookup.value):
            yield key.identifier
            next = cursor.next()
        else:
            # it can mean that:
            #
            #   key.attribute != lookup.attribute
            #
            # which means there is no more document indexed
            # with this attribute, no need to iterate over more
            # keys
            #
            # or that:
            #
            #   key.value != lookup.value
            #
            # They are some document that have a value for
            # ``lookup.attribute`` but ``key.value`` is not
            # what we look for and will never be anymore since
            # the index is ordered.
            #
            # In both case, there is no more matching documents.
            break
```

HTH

**Comment by jtgrassie** [comment]
Is there a reason `mdb_set_compare`  and `mdb_set_dupsort` couldn't be exposed to make use of [ctypes](https://docs.python.org/3/library/ctypes.html)? That way the comparison functions can be supplied by Python, like in the docs: https://docs.python.org/3/library/ctypes.html#callback-functions.

**Comment by jnwatson** [comment]
All the reasons dw explained stand. It would be extraordinarily slow and expose the user to unintended database corruption if the database was ever opened by any client code that didn't have the new comparison installed.

I'll add another one: the mdb_set_compare isn't well tested in the upstream. I'm not aware of any other code that uses it.

**Comment by jtgrassie** [comment]
> I'll add another one: the mdb_set_compare isn't well tested in the upstream. I'm not aware of any other code that uses it.

A very odd comment. It's thoroughly tested and in use in openldap to name one.

> It would be extraordinarily slow 

Apologies but why? You have concerns over the ctypes implementation mentioned?

> and expose the user to unintended database corruption if the database was ever opened by any client code that didn't have the new comparison installed.

Which is precisely the same thing you expose users to if they use pylmdb on a database that *is already* using mdb_set_compare / mdb_set_dupsort. Right now, this project is largely unusable for databases created outside of pylmdb because of this.

**Comment by dw** [comment]
Hey @jtgrassie, the question of why was already answered 8 years ago. Feel free to propose a PR and corresponding performance benchmark demonstrating the answer is false if you have reason to doubt it. I think it could be reasonable to support dupsort for the sake of feature completeness, but not at severe cost to normal usage of the binding, where most users have originally been attracted to use it due to its performance characteristics. Both CPython and CFFI are very likely to show substantial slowdowns for all code, even code that not using a custom key function, but I'm very happy to be proven wrong.

**Comment by jtgrassie** [comment]
Thanks @dw, that gets me nearer to the answer. 

> Both CPython and CFFI are very likely to show substantial slowdowns for all code, even code that not using a custom key function, but I'm very happy to be proven wrong.

I've had a look over the code and believe a patch can be written which whereby there can be zero impact for a users *not* supplying custom compare functions, which leaves me at implementing and measuring then. I agree there's likely going to be *some* slowdown when using a python side comparison functions, the question is therefore *how much* and if anyone had attempted to quantify before (testing different approaches, e.g. ctypes vs CFFI callbacks). When I get a spare weekend I'll give it a crack then.
