### ISSUE TITLE
Named database not working

### ISSUE THREAD

**Issue by kvikas** [dw/py-lmdb#87]
Either they are not working or I don't know how to use named databases. I think it is the later. If that is the case let me know what am I doing wrong. Do I need to create a named database before I can use it or they get created on the fly when one is requested?

Here is a sample code:

```python
>>> from lmdb import Environment
>>> env = Environment('./store', max_dbs = 16)

>>> with env.begin(db = 'db1') as txn:
...     txn.get('key1')
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid type

>>> with env.begin() as txn:
...     txn.get('key1', db = 'db1')
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: invalid type
```

Also:
```bash
$ pip freeze | grep lmdb
lmdb==0.84
```

**Comment by dw** [comment]
Hi Vikas,

You need to create it using Environment.open_db().. Check the documentation. If using open_db() inside a transaction, you must pass the transaction as an argument.

-----Original Message-----

**Comment by kvikas** [comment]
Thanks dw. This worked:

```
>>> from lmdb import Environment
>>> env = Environment('./store', max_dbs = 16)
>>> db1 = env.open_db('db1')
>>> with env.begin(db = db1) as txn:
...     txn.get('key1')
...
>>>
```
