### ISSUE TITLE
Environment objects leak memory

### ISSUE THREAD

**Issue by josvos** [dw/py-lmdb#88]
When opening and closing an LMDB DB many times in a loop (I did this for performance tests), the program size gets bigger and bigger.  Looking with the Python garbage collector (gc.collect()) gives the following message for every lmdb.cffi.Environment object ever created with lmdb.open() (and closed with env.close()): "An object which the collector found to be unreachable but could not be freed (uncollectable objects)."

**Comment by dw** [comment]
Hi Jos,

Thanks for the report. This sounds like a simple bug, I'll have a look ASAP (hopefully tonight or tomorrow, but just started a fresh contract so might take a few days).

Did you try with the native CPython binding? What Python implementation and version were you using?

**Comment by josvos** [comment]
I tested it on Fedora 21 with Python 2.7.8.

With CPython I can't close a Cursor object ("AttributeError: 'Cursor' object has no attribute 'close'") and when I don't close it, I also see the process growing and growing, although the Python garbage collector doesn't report problems there.

**Comment by dw** [comment]
Hi Jos,

Once again thanks for the report. The problem is that on CFFI, lmdb.cffi._Database holds a strong reference to the Environment object, apparently causing a cycle. Explicitly calling Environment.close() breaks this cycle.

Alternatively the problem does not exist in the CPython extension. There I have added the missing Cursor.close(). CPython's Cursor object had ``__enter__`` and ``__exit__`` added, but I forgot to add .close(). Another case of being bitten by an incomplete test suite :)

I will investigate how to fix the CFFI reference cycle sometime this weekend. For now just invoke Environment.close() explicitly

**Comment by josvos** [comment]
What do you mean with invoking Environment.close() explicitly?

**Comment by dw** [comment]
Hi Jos,

You have opened a pandoras box :)  Both CPython and CFFI have problems here. This will take me a couple more days to fix (ETA at least this weekend).

Again thanks for the report.

**Comment by dw** [comment]
Hi again,

The current master version seems good now. There was a separate bug where weakrefs weren't being invalidated that was causing issues on CPython. Can you retest and confirm? If not, I will play a little more before cutting a release, there's a bunch of LMDB engine fixes sitting in master too.

**Comment by josvos** [comment]
The memory leak seems to be gone, but I can't compile it with a system lmdb (LMDB_FORCE_SYSTEM=1).  I thought I could in the past, but I'm not sure.  I now get:

**Comment by dw** [comment]
Hi Jos,

Thanks for this. Yep, I can see why that is broken. Will make another release sometime this evening to fix it.

**Comment by xayam** [comment]
> Thanks for this. Yep, I can see why that is broken. Will make another release sometime this evening to fix it.

I tried to create an Environment many times using open_db and over time the RAM costs increased to the limit, but if I alternate opening the Environment first for writing and then for reading, then the memory is freed and everything is fine
