### ISSUE TITLE
key sorting

### ISSUE THREAD

**Issue by stephane-martin** [dw/py-lmdb#91]
Hello,

the docs say that LMDB keep database keys sorted, but dont specify what kind of order is used. Looking at LMDB API i understand that the lexicographic order is used by default. This is not neutral, as "11" < "2" in lexicographic order. When traversring the DB with a cursor iterator it makes a sensible difference. So: 

- py-lmdb docs should explicity state that the lexicographic order is used
- bonus: py-lmdb could provide a way to specify an alternater order, by providing a python comparison function (for example to switch to plain integer comparison)

Thanks for the good work,
Stephane

**Comment by dw** [comment]
Hi Stephane,

See http://lmdb.readthedocs.org/en/latest/#deviations-from-lmdb-api for information about custom sorting methods. The short answer is they're dangerous, too slow, and in the usual case can be replaced by a custom key encoding that will always be faster.

**Comment by stephane-martin** [comment]
Understood :) My main point was that the words "lexicographic order" should
appear somewhere in docs.

2015-06-08 8:54 GMT+02:00 dw <notifications@github.com>:
