### ISSUE TITLE
Error while installing lmdb in python

### ISSUE THREAD

**Issue by shubham-pachori** [dw/py-lmdb#95]
![untitled](https://cloud.githubusercontent.com/assets/13487962/8881723/877f5a94-325f-11e5-8043-da9d25f56e56.png)

I am getting the error as shown in the figure while installing lmdb. Could somebody please help me through this. I am using Anaconda with 64- bit version in windows.

Thanks

**Comment by dw** [comment]
Hi there,

Can you please retry using pip. I have recently uploaded binary wheels and eggs for v0.86 to PyPI, so you should not need to have a compiler setup on the machine you are installing to.


David

**Comment by dw** [comment]
i.e. "pip install lmdb", "easy_install lmdb", "python -m pip install lmdb", "python -m easy_install lmdb". At least one of these commands should 'just work' :)
