### ISSUE TITLE
InvalidParameterError: mdb_env_set_mapsize: Invalid argument

### ISSUE THREAD

**Issue by lukeyeager** [dw/py-lmdb#97]
Thanks for pushing out a new version! The new `set_mapsize` function in 442096e1551e204894154436877080a5b2571813  will be a great help for https://github.com/NVIDIA/DIGITS/issues/206.

... but it's not working for me. Am I doing something stupid?

```
# Try doubling
  File "./create_db.py", line 466, in write_batch
    self.db.set_mapsize(curr_limit*2)
InvalidParameterError: mdb_env_set_mapsize: Invalid argument

# Try 50MB
  File "./create_db.py", line 466, in write_batch
    self.db.set_mapsize(50*1024*1024)
InvalidParameterError: mdb_env_set_mapsize: Invalid argument

# Try a string
  File "./create_db.py", line 466, in write_batch
    self.db.set_mapsize('f')
OverflowError: Integer argument exceeds limit.
```
More context:
https://github.com/lukeyeager/DIGITS/blob/e5c16d2517/tools/create_db.py#L444-L471

My version:
```python
>>> import lmdb
>>> lmdb.__version__
'0.87'
>>> lmdb.version()
(0, 9, 14)
```

**Comment by dw** [comment]
Hi Luke,

Are you calling it from within a write transaction? That looks like the only case where MDB will return EINVAL. There must be no active transactions within the current process when you invoke set_mapsize().

Sorry, I just opened a todo ticket to add these checks later, since ensuring they're correct is quite complicated, so the initial version just defers to the LMDB docs :)

**Comment by dw** [comment]
Whoops, yes, seems you are. You probably want to move the exception handler up one level and wrap the whole thing in a ``while True: ; ... ; break ``  (with the exception handler executing ``continue`` instead)

**Comment by lukeyeager** [comment]
> Are you calling it from within a write transaction?

Yep, adding a call to `lmdb_txn.abort()` did the trick, thanks!

Can you tell me what would happen if one thread tries to set the mapsize while another thread is in the middle of committing a transaction? I want to use multiple write threads and still ensure thread-safety.

**Comment by dw** [comment]
Hi Luke,

The EINVAL test appears to pretty much be a best effort attempt at preventing you from shooting yourself in the foot: it does not take the environment write lock, and so there is no synchronization between it and writes whatsoever -- these are checks I will eventually add to the binding.

It is possible that a new write transaction will race with set_mapsize() such that:

1. set_mapsize() checks for active transaction. There is none - OK.
2. Write transaction starts, updates environment struct to indicate it is active.
3. set_mapsize() updates the map size field, and calls munmap()
4. Write transaction starts comit, attempts to read from map.
5. Map does not exist, write triggers SEGV.
6. set_mapsize() installs newly resized map, possibly moves map address in RAM.

As you see, it's not safe at all -- you must provide your own synchronization to avoid this (a `threading.Lock` would suffice, and would not produce much slowdown at all), or just write from one thread.

A context manager like this could work:

````python
import threading
import contextlib

lmdb_global_write_lock = threading.Lock()

@contextlib.contextmanager
def lmdb_write_txn(env):
    with lmdb_global_write_lock:
        with env.begin(write=True) as txn:
            yield txn


# Now, each thread simply creates a write txn like this instead:
with lmdb_write_txn(env) as txn:
     pass


# A thread attempting to map resize would do this:
with lmdb_global_write_lock:
    env.set_mapsize()
````

Note the problem also affects readers. Really this needs done inside the binding, but for the time being if you're careful it shouldn't be a problem, just requires a bit of fiddly coding.

**Comment by lukeyeager** [comment]
@dw, thanks for the great explanation!

After running more performance tests, it turns out having more than one write thread doesn't actually help as much as I thought it did. I'm going to keep it simple for now and just use a single thread for writing to LMDB.

**Comment by hyc** [comment]
Indeed, LMDB is a single-writer design so you wouldn't see any performance gain using multiple writer threads.

**Comment by lukeyeager** [comment]
Oh, well then that makes sense. Thanks for the clarification!
